/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bl.wordcounter.webapp.Service;

import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import org.springframework.stereotype.Service;

/**
 *
 * @author Boone
 */
@Service
public class MailServiceImpl implements MailService {
    
    @Override
    public void sendForgotPassword(String recipientAddress, String newPassword) throws Exception {
        Properties properties = new Properties();
        
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.host", "smtp.gmail.com");
        properties.put("mail.smtp.port", "587");
        
        String myAccountEmail = "BenLeBoot@gmail.com";
        String myPassword = "password";
        
        Session session = Session.getInstance(properties, new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(myAccountEmail, myPassword);
            }
        });
        
        String subject = "DO NOT REPLY from WordCounter.com: Forgot Password Notification";
        
        String text = "This is an autogenerated email from WordCounter.com.  Do not reply."
                + "\n Your account's password has been reset."
                + "\n Your temporary password is " + newPassword
                + "\n Please change your password once you log in.";
        
        Message message = prepareMessage(session, myAccountEmail, recipientAddress, subject, text);
        
        Transport.send(message);
        
    }
    
     
    
    private Message prepareMessage(Session session, String myAccountEmail, String recipientAddress, String subject, String text) throws Exception {
        Message message = new MimeMessage(session);
      
        message.setFrom(new InternetAddress(myAccountEmail));
        message.setRecipient(Message.RecipientType.TO, new InternetAddress(recipientAddress));
        message.setSubject(subject);
        message.setText(text);
        return message;
    }
    
}
